In [1]:
import pandas as pd  # Import Pandas  

# Create a small dataset  
data = {"Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35]}  
df = pd.DataFrame(data)  # Convert dictionary to DataFrame  

print(df)  # Display the dataset

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [2]:
#filter df by age greater than 30
df[df['Age'] > 30]

      Name  Age
2  Charlie   35

In [3]:
#Mean of Ages
df['Age'].mean()

np.float64(30.0)

In [6]:
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 195.0 bytes